# Generated by Django 5.2.17 on 2026-10-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_selected',
            new_name='on_list',
        ),
    ]
